server:
  port: 9001

spring:
  datasource:
    dbcp2:
      driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.128:3306/curso?serverTimezone=UTC
    username: root
    password: admin
  jpa: #para que hibernate cree adecuadamente las instrucciones SQL
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.128:8761/eureka
  instance:
    instance-id: ${random.value}:${spring.application.name}      
